version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/site:rw
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80" # 正式部署改为绑定外部 80
    volumes:
      - ./static:/site/static:cached
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:cached
    depends_on:
      - app

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${RIDDLE_PASSWORD}
      POSTGRES_USER: ${RIDDLE_USER}
      POSTGRES_DB: ${RIDDLE_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    restart: always
    image: redis
