version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/site:rw
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./static:/site/static:cached
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:cached

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    restart: always
    image: redis
