version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/site:rw
      - ~/repos/cert:/cert/
    depends_on:
      - postgres
      - redis
      - pgbouncer

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8001:80" # 正式部署改为绑定外部 80
    volumes:
      - ./static:/site/static:cached
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:cached
    depends_on:
      - app

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${RIDDLE_PASSWORD}
      POSTGRES_USER: ${RIDDLE_USER}
      POSTGRES_DB: ${RIDDLE_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata

  pgbouncer:
    image: pgbouncer/pgbouncer
    environment:
      DATABASES_HOST: postgres
      DATABASES_USER: ${RIDDLE_USER}           # define credentials
      DATABASES_PASSWORD: ${RIDDLE_PASSWORD}       # define credentials
      DATABASES_PORT: 5432               # define database
      DATABASES_DBNAME: ${RIDDLE_NAME}
      PGBOUNCER_AUTH_TYPE: md5
      PGBOUNCER_AUTH_FILE: /etc/pgbouncer/userlist.txt
      PGBOUNCER_ADMIN_USERS: ${RIDDLE_USER}
    links:
      - postgres:postgres
    ports:
      - 6432:6432                 # PgBouncer port
    volumes:
      - ./conf/pgbouncer:/etc/pgbouncer
    depends_on:
      - postgres

  redis:
    restart: always
    image: redis
